### ISSUE TITLE
monad-control-1.0 fails to compile with GHC 7.0.4 & GHC 7.2.2

### ISSUE THREAD

**Issue by hvr** [basvandijk/monad-control#25]
(see also https://ghc.haskell.org/~hvr/buildreports/monad-control.html)

Please either add a `base >= 4.5` constraint to future releases, or make it compatible with GHC 7.0 again.

```
Preprocessing library monad-control-1.0.0.1...
[1 of 1] Compiling Control.Monad.Trans.Control ( Control/Monad/Trans/Control.hs, dist/dist-sandbox-4ac2267c/build/Control/Monad/Trans/Control.o )

Control/Monad/Trans/Control.hs:113:3:
    Not in scope: type variable `a'

Control/Monad/Trans/Control.hs:297:5:
    Not in scope: type variable `a'
Failed to install monad-control-1.0.0.1
cabal: Error: some packages failed to install:
monad-control-1.0.0.1 failed during the building phase. The exception was:
ExitFailure 1
```

**Comment by basvandijk** [comment]
monad-control >= 1.0 can't be made compatible with GHC < 7.4 so I went with your first advise of adding a base >= 4.5 constraint. Released as [monad-control-1.0.0.2](http://hackage.haskell.org/package/monad-control-1.0.0.2).

**Comment by hvr** [comment]
@basvandijk We also need to retrofit the `base >= 4.5` constraint to the two previous releases:

- https://hackage.haskell.org/package/monad-control-1.0.0.0/monad-control.cabal/edit
- https://hackage.haskell.org/package/monad-control-1.0.0.1/monad-control.cabal/edit

otherwise `cabal install monad-control` (as well as any build-plan involving `monad-control <= 1.1`) will still pick `1.0.0.1` on GHC 7.0 and `1.0.0.0` on GHC 7.2... 

(You can see the effect on https://ghc.haskell.org/~hvr/buildreports/monad-control.html  which I've just regenerated)

**Comment by basvandijk** [comment]
Done. Thanks for the tip!

**Comment by hvr** [comment]
Fyi, unbreaking `monad-control` also unbroke `resource-pool` for GHC 7.0 & 7.2 users :-)
